// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package gameProto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ChatREQ struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatREQ) Reset()         { *m = ChatREQ{} }
func (m *ChatREQ) String() string { return proto.CompactTextString(m) }
func (*ChatREQ) ProtoMessage()    {}
func (*ChatREQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *ChatREQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatREQ.Unmarshal(m, b)
}
func (m *ChatREQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatREQ.Marshal(b, m, deterministic)
}
func (m *ChatREQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatREQ.Merge(m, src)
}
func (m *ChatREQ) XXX_Size() int {
	return xxx_messageInfo_ChatREQ.Size(m)
}
func (m *ChatREQ) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatREQ.DiscardUnknown(m)
}

var xxx_messageInfo_ChatREQ proto.InternalMessageInfo

func (m *ChatREQ) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ChatACK struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatACK) Reset()         { *m = ChatACK{} }
func (m *ChatACK) String() string { return proto.CompactTextString(m) }
func (*ChatACK) ProtoMessage()    {}
func (*ChatACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *ChatACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatACK.Unmarshal(m, b)
}
func (m *ChatACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatACK.Marshal(b, m, deterministic)
}
func (m *ChatACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatACK.Merge(m, src)
}
func (m *ChatACK) XXX_Size() int {
	return xxx_messageInfo_ChatACK.Size(m)
}
func (m *ChatACK) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatACK.DiscardUnknown(m)
}

var xxx_messageInfo_ChatACK proto.InternalMessageInfo

func (m *ChatACK) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type TestACK struct {
	Dummy                string   `protobuf:"bytes,1,opt,name=Dummy,proto3" json:"Dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestACK) Reset()         { *m = TestACK{} }
func (m *TestACK) String() string { return proto.CompactTextString(m) }
func (*TestACK) ProtoMessage()    {}
func (*TestACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *TestACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestACK.Unmarshal(m, b)
}
func (m *TestACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestACK.Marshal(b, m, deterministic)
}
func (m *TestACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestACK.Merge(m, src)
}
func (m *TestACK) XXX_Size() int {
	return xxx_messageInfo_TestACK.Size(m)
}
func (m *TestACK) XXX_DiscardUnknown() {
	xxx_messageInfo_TestACK.DiscardUnknown(m)
}

var xxx_messageInfo_TestACK proto.InternalMessageInfo

func (m *TestACK) GetDummy() string {
	if m != nil {
		return m.Dummy
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatREQ)(nil), "gameProto.ChatREQ")
	proto.RegisterType((*ChatACK)(nil), "gameProto.ChatACK")
	proto.RegisterType((*TestACK)(nil), "gameProto.TestACK")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x4f, 0xcc, 0x4d, 0x0d, 0x00, 0x31, 0x95,
	0x94, 0xb9, 0xd8, 0x9d, 0x33, 0x12, 0x4b, 0x82, 0x5c, 0x03, 0x85, 0x24, 0xb8, 0xd8, 0x9d, 0xf3,
	0xf3, 0x4a, 0x52, 0xf3, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x98, 0x22,
	0x47, 0x67, 0x6f, 0x3c, 0x8a, 0xe4, 0xb9, 0xd8, 0x43, 0x52, 0x8b, 0xc1, 0x8a, 0x44, 0xb8, 0x58,
	0x5d, 0x4a, 0x73, 0x73, 0x2b, 0xa1, 0x4a, 0x20, 0x9c, 0x24, 0x36, 0xb0, 0xe5, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x19, 0x91, 0xe1, 0x7b, 0x8a, 0x00, 0x00, 0x00,
}
