// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub.proto

package gameProto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubscribeChannelREQ struct {
	Channel              string   `protobuf:"bytes,1,opt,name=Channel,proto3" json:"Channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeChannelREQ) Reset()         { *m = SubscribeChannelREQ{} }
func (m *SubscribeChannelREQ) String() string { return proto.CompactTextString(m) }
func (*SubscribeChannelREQ) ProtoMessage()    {}
func (*SubscribeChannelREQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{0}
}

func (m *SubscribeChannelREQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeChannelREQ.Unmarshal(m, b)
}
func (m *SubscribeChannelREQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeChannelREQ.Marshal(b, m, deterministic)
}
func (m *SubscribeChannelREQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeChannelREQ.Merge(m, src)
}
func (m *SubscribeChannelREQ) XXX_Size() int {
	return xxx_messageInfo_SubscribeChannelREQ.Size(m)
}
func (m *SubscribeChannelREQ) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeChannelREQ.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeChannelREQ proto.InternalMessageInfo

func (m *SubscribeChannelREQ) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type SubscribeChannelACK struct {
	Channel              string   `protobuf:"bytes,1,opt,name=Channel,proto3" json:"Channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeChannelACK) Reset()         { *m = SubscribeChannelACK{} }
func (m *SubscribeChannelACK) String() string { return proto.CompactTextString(m) }
func (*SubscribeChannelACK) ProtoMessage()    {}
func (*SubscribeChannelACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{1}
}

func (m *SubscribeChannelACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeChannelACK.Unmarshal(m, b)
}
func (m *SubscribeChannelACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeChannelACK.Marshal(b, m, deterministic)
}
func (m *SubscribeChannelACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeChannelACK.Merge(m, src)
}
func (m *SubscribeChannelACK) XXX_Size() int {
	return xxx_messageInfo_SubscribeChannelACK.Size(m)
}
func (m *SubscribeChannelACK) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeChannelACK.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeChannelACK proto.InternalMessageInfo

func (m *SubscribeChannelACK) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

type SvcStatusACK struct {
	SvcID                string   `protobuf:"bytes,1,opt,name=SvcID,proto3" json:"SvcID,omitempty"`
	UserCount            int32    `protobuf:"varint,2,opt,name=UserCount,proto3" json:"UserCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SvcStatusACK) Reset()         { *m = SvcStatusACK{} }
func (m *SvcStatusACK) String() string { return proto.CompactTextString(m) }
func (*SvcStatusACK) ProtoMessage()    {}
func (*SvcStatusACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{2}
}

func (m *SvcStatusACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SvcStatusACK.Unmarshal(m, b)
}
func (m *SvcStatusACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SvcStatusACK.Marshal(b, m, deterministic)
}
func (m *SvcStatusACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SvcStatusACK.Merge(m, src)
}
func (m *SvcStatusACK) XXX_Size() int {
	return xxx_messageInfo_SvcStatusACK.Size(m)
}
func (m *SvcStatusACK) XXX_DiscardUnknown() {
	xxx_messageInfo_SvcStatusACK.DiscardUnknown(m)
}

var xxx_messageInfo_SvcStatusACK proto.InternalMessageInfo

func (m *SvcStatusACK) GetSvcID() string {
	if m != nil {
		return m.SvcID
	}
	return ""
}

func (m *SvcStatusACK) GetUserCount() int32 {
	if m != nil {
		return m.UserCount
	}
	return 0
}

type ServiceIdentifyACK struct {
	SvcName              string   `protobuf:"bytes,1,opt,name=SvcName,proto3" json:"SvcName,omitempty"`
	SvcID                string   `protobuf:"bytes,2,opt,name=SvcID,proto3" json:"SvcID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceIdentifyACK) Reset()         { *m = ServiceIdentifyACK{} }
func (m *ServiceIdentifyACK) String() string { return proto.CompactTextString(m) }
func (*ServiceIdentifyACK) ProtoMessage()    {}
func (*ServiceIdentifyACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3103f8d3056b01c, []int{3}
}

func (m *ServiceIdentifyACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceIdentifyACK.Unmarshal(m, b)
}
func (m *ServiceIdentifyACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceIdentifyACK.Marshal(b, m, deterministic)
}
func (m *ServiceIdentifyACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceIdentifyACK.Merge(m, src)
}
func (m *ServiceIdentifyACK) XXX_Size() int {
	return xxx_messageInfo_ServiceIdentifyACK.Size(m)
}
func (m *ServiceIdentifyACK) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceIdentifyACK.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceIdentifyACK proto.InternalMessageInfo

func (m *ServiceIdentifyACK) GetSvcName() string {
	if m != nil {
		return m.SvcName
	}
	return ""
}

func (m *ServiceIdentifyACK) GetSvcID() string {
	if m != nil {
		return m.SvcID
	}
	return ""
}

func init() {
	proto.RegisterType((*SubscribeChannelREQ)(nil), "gameProto.SubscribeChannelREQ")
	proto.RegisterType((*SubscribeChannelACK)(nil), "gameProto.SubscribeChannelACK")
	proto.RegisterType((*SvcStatusACK)(nil), "gameProto.SvcStatusACK")
	proto.RegisterType((*ServiceIdentifyACK)(nil), "gameProto.ServiceIdentifyACK")
}

func init() { proto.RegisterFile("hub.proto", fileDescriptor_b3103f8d3056b01c) }

var fileDescriptor_b3103f8d3056b01c = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x28, 0x4d, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x4f, 0xcc, 0x4d, 0x0d, 0x00, 0x31, 0x95, 0xf4,
	0xb9, 0x84, 0x83, 0x4b, 0x93, 0x8a, 0x93, 0x8b, 0x32, 0x93, 0x52, 0x9d, 0x33, 0x12, 0xf3, 0xf2,
	0x52, 0x73, 0x82, 0x5c, 0x03, 0x85, 0x24, 0xb8, 0xd8, 0xa1, 0x3c, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x18, 0x17, 0x9b, 0x06, 0x47, 0x67, 0x6f, 0x3c, 0x1a, 0x9c, 0xb8, 0x78, 0x82, 0xcb,
	0x92, 0x83, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x41, 0x2a, 0x45, 0xb8, 0x58, 0x83, 0xcb, 0x92, 0x3d,
	0x5d, 0xa0, 0xea, 0x20, 0x1c, 0x21, 0x19, 0x2e, 0xce, 0xd0, 0xe2, 0xd4, 0x22, 0xe7, 0xfc, 0xd2,
	0xbc, 0x12, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x84, 0x80, 0x92, 0x0b, 0x97, 0x50, 0x70,
	0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x67, 0x4a, 0x6a, 0x5e, 0x49, 0x66, 0x5a, 0x25, 0xd4, 0xce,
	0xe0, 0xb2, 0x64, 0xbf, 0xc4, 0xdc, 0x54, 0x98, 0x9d, 0x50, 0x2e, 0xc2, 0x0e, 0x26, 0x24, 0x3b,
	0x92, 0xd8, 0xc0, 0xbe, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x23, 0x97, 0x40, 0x0a,
	0x01, 0x00, 0x00,
}
