@echo off
echo Stopping login...
taskkill /F /IM login.exe > nul
echo Stopping gate...
taskkill /F /IM gate.exe > nul
echo Stopping game...
taskkill /F /IM game.exe > nul
::echo Stopping hub...
::taskkill /F /IM hub.exe > nul
pause