// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package msgProto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerInfo struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ServerInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type PingAck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingAck) Reset()         { *m = PingAck{} }
func (m *PingAck) String() string { return proto.CompactTextString(m) }
func (*PingAck) ProtoMessage()    {}
func (*PingAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *PingAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingAck.Unmarshal(m, b)
}
func (m *PingAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingAck.Marshal(b, m, deterministic)
}
func (m *PingAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingAck.Merge(m, src)
}
func (m *PingAck) XXX_Size() int {
	return xxx_messageInfo_PingAck.Size(m)
}
func (m *PingAck) XXX_DiscardUnknown() {
	xxx_messageInfo_PingAck.DiscardUnknown(m)
}

var xxx_messageInfo_PingAck proto.InternalMessageInfo

type LoginReq struct {
	Version              string   `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Platform             string   `protobuf:"bytes,2,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LoginReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LoginReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type LoginAck struct {
	Result               ResultCode  `protobuf:"varint,1,opt,name=Result,proto3,enum=msgProto.ResultCode" json:"Result,omitempty"`
	Server               *ServerInfo `protobuf:"bytes,2,opt,name=Server,proto3" json:"Server,omitempty"`
	GameToken            string      `protobuf:"bytes,3,opt,name=GameToken,proto3" json:"GameToken,omitempty"`
	GameSvcId            string      `protobuf:"bytes,4,opt,name=GameSvcId,proto3" json:"GameSvcId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LoginAck) Reset()         { *m = LoginAck{} }
func (m *LoginAck) String() string { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()    {}
func (*LoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *LoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAck.Unmarshal(m, b)
}
func (m *LoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAck.Marshal(b, m, deterministic)
}
func (m *LoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAck.Merge(m, src)
}
func (m *LoginAck) XXX_Size() int {
	return xxx_messageInfo_LoginAck.Size(m)
}
func (m *LoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAck proto.InternalMessageInfo

func (m *LoginAck) GetResult() ResultCode {
	if m != nil {
		return m.Result
	}
	return ResultCode_NoError
}

func (m *LoginAck) GetServer() *ServerInfo {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *LoginAck) GetGameToken() string {
	if m != nil {
		return m.GameToken
	}
	return ""
}

func (m *LoginAck) GetGameSvcId() string {
	if m != nil {
		return m.GameSvcId
	}
	return ""
}

type VerifyReq struct {
	GameToken            string   `protobuf:"bytes,1,opt,name=GameToken,proto3" json:"GameToken,omitempty"`
	GameSvcId            string   `protobuf:"bytes,2,opt,name=GameSvcId,proto3" json:"GameSvcId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyReq) Reset()         { *m = VerifyReq{} }
func (m *VerifyReq) String() string { return proto.CompactTextString(m) }
func (*VerifyReq) ProtoMessage()    {}
func (*VerifyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *VerifyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyReq.Unmarshal(m, b)
}
func (m *VerifyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyReq.Marshal(b, m, deterministic)
}
func (m *VerifyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyReq.Merge(m, src)
}
func (m *VerifyReq) XXX_Size() int {
	return xxx_messageInfo_VerifyReq.Size(m)
}
func (m *VerifyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyReq proto.InternalMessageInfo

func (m *VerifyReq) GetGameToken() string {
	if m != nil {
		return m.GameToken
	}
	return ""
}

func (m *VerifyReq) GetGameSvcId() string {
	if m != nil {
		return m.GameSvcId
	}
	return ""
}

type VerifyAck struct {
	Result               ResultCode `protobuf:"varint,1,opt,name=Result,proto3,enum=msgProto.ResultCode" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VerifyAck) Reset()         { *m = VerifyAck{} }
func (m *VerifyAck) String() string { return proto.CompactTextString(m) }
func (*VerifyAck) ProtoMessage()    {}
func (*VerifyAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{5}
}

func (m *VerifyAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyAck.Unmarshal(m, b)
}
func (m *VerifyAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyAck.Marshal(b, m, deterministic)
}
func (m *VerifyAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyAck.Merge(m, src)
}
func (m *VerifyAck) XXX_Size() int {
	return xxx_messageInfo_VerifyAck.Size(m)
}
func (m *VerifyAck) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyAck.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyAck proto.InternalMessageInfo

func (m *VerifyAck) GetResult() ResultCode {
	if m != nil {
		return m.Result
	}
	return ResultCode_NoError
}

func init() {
	proto.RegisterType((*ServerInfo)(nil), "msgProto.ServerInfo")
	proto.RegisterType((*PingAck)(nil), "msgProto.PingAck")
	proto.RegisterType((*LoginReq)(nil), "msgProto.LoginReq")
	proto.RegisterType((*LoginAck)(nil), "msgProto.LoginAck")
	proto.RegisterType((*VerifyReq)(nil), "msgProto.VerifyReq")
	proto.RegisterType((*VerifyAck)(nil), "msgProto.VerifyAck")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x49, 0x37, 0xb7, 0xe6, 0x4d, 0x86, 0x04, 0x0f, 0x61, 0x78, 0x18, 0x39, 0xed, 0x20,
	0x45, 0xf4, 0xe4, 0x71, 0x78, 0x18, 0x05, 0x0f, 0x25, 0xd3, 0xdd, 0x67, 0x9b, 0x96, 0xd0, 0x36,
	0xa9, 0x69, 0x1d, 0xf8, 0xef, 0xf8, 0x97, 0x4a, 0xd2, 0xd4, 0xaa, 0x07, 0xc1, 0xdb, 0x7b, 0xdf,
	0xfb, 0xf2, 0x7b, 0xef, 0x23, 0xb0, 0xa8, 0x74, 0x21, 0x55, 0xd4, 0x18, 0xdd, 0x69, 0x12, 0xd6,
	0x6d, 0x91, 0xd8, 0x6a, 0x75, 0x6e, 0x44, 0xfb, 0x56, 0x75, 0xbd, 0xce, 0x6e, 0x00, 0xf6, 0xc2,
	0x9c, 0x84, 0x89, 0x55, 0xae, 0xc9, 0x12, 0x82, 0xb8, 0xa1, 0x68, 0x8d, 0x36, 0x98, 0x07, 0x71,
	0x43, 0x08, 0x4c, 0x13, 0x6d, 0x3a, 0x1a, 0xac, 0xd1, 0xe6, 0x8c, 0xbb, 0x9a, 0x61, 0x98, 0x27,
	0x52, 0x15, 0xdb, 0xb4, 0x64, 0x1c, 0xc2, 0x47, 0xbb, 0x83, 0x8b, 0x57, 0x42, 0x61, 0x7e, 0x10,
	0xa6, 0x95, 0x5a, 0xf9, 0xf7, 0x43, 0x4b, 0x56, 0x10, 0x26, 0xd5, 0xb1, 0xcb, 0xb5, 0xa9, 0x1d,
	0x08, 0xf3, 0xaf, 0x9e, 0x5c, 0xc0, 0xe4, 0x59, 0x66, 0x74, 0xe2, 0x64, 0x5b, 0xb2, 0x0f, 0xe4,
	0xa1, 0xdb, 0xb4, 0x24, 0xd7, 0x30, 0xe3, 0xee, 0x5a, 0xc7, 0x5c, 0xde, 0x5e, 0x46, 0x43, 0x8c,
	0xa8, 0xd7, 0x1f, 0x74, 0x26, 0xb8, 0xf7, 0x58, 0x77, 0x9f, 0xc5, 0xad, 0x59, 0x7c, 0x77, 0x8f,
	0x19, 0xb9, 0xf7, 0x90, 0x2b, 0xc0, 0xbb, 0x63, 0x2d, 0x9e, 0x74, 0x29, 0x94, 0x3f, 0x60, 0x14,
	0x86, 0xe9, 0xfe, 0x94, 0xc6, 0x19, 0x9d, 0x8e, 0x53, 0x27, 0xb0, 0x1d, 0xe0, 0x83, 0x30, 0x32,
	0x7f, 0xb7, 0xc9, 0x7f, 0x80, 0xd0, 0x9f, 0xa0, 0xe0, 0x37, 0xe8, 0x7e, 0x00, 0xfd, 0x3b, 0xed,
	0xcb, 0xcc, 0x7d, 0xe0, 0xdd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x07, 0x55, 0x97, 0xeb, 0xe7,
	0x01, 0x00, 0x00,
}
