// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RemoteCallReq struct {
	MsgId                int32    `protobuf:"varint,1,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	CallId               int64    `protobuf:"varint,3,opt,name=CallId,proto3" json:"CallId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteCallReq) Reset()         { *m = RemoteCallReq{} }
func (m *RemoteCallReq) String() string { return proto.CompactTextString(m) }
func (*RemoteCallReq) ProtoMessage()    {}
func (*RemoteCallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *RemoteCallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteCallReq.Unmarshal(m, b)
}
func (m *RemoteCallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteCallReq.Marshal(b, m, deterministic)
}
func (m *RemoteCallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteCallReq.Merge(m, src)
}
func (m *RemoteCallReq) XXX_Size() int {
	return xxx_messageInfo_RemoteCallReq.Size(m)
}
func (m *RemoteCallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteCallReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteCallReq proto.InternalMessageInfo

func (m *RemoteCallReq) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *RemoteCallReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RemoteCallReq) GetCallId() int64 {
	if m != nil {
		return m.CallId
	}
	return 0
}

type RemoteCallAck struct {
	MsgId                int32    `protobuf:"varint,1,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	CallId               int64    `protobuf:"varint,3,opt,name=CallId,proto3" json:"CallId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteCallAck) Reset()         { *m = RemoteCallAck{} }
func (m *RemoteCallAck) String() string { return proto.CompactTextString(m) }
func (*RemoteCallAck) ProtoMessage()    {}
func (*RemoteCallAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *RemoteCallAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteCallAck.Unmarshal(m, b)
}
func (m *RemoteCallAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteCallAck.Marshal(b, m, deterministic)
}
func (m *RemoteCallAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteCallAck.Merge(m, src)
}
func (m *RemoteCallAck) XXX_Size() int {
	return xxx_messageInfo_RemoteCallAck.Size(m)
}
func (m *RemoteCallAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteCallAck.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteCallAck proto.InternalMessageInfo

func (m *RemoteCallAck) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *RemoteCallAck) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RemoteCallAck) GetCallId() int64 {
	if m != nil {
		return m.CallId
	}
	return 0
}

func init() {
	proto.RegisterType((*RemoteCallReq)(nil), "rpc.RemoteCallReq")
	proto.RegisterType((*RemoteCallAck)(nil), "rpc.RemoteCallAck")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2a, 0x48, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0x0a, 0xe4, 0xe2, 0x0d, 0x4a,
	0xcd, 0xcd, 0x2f, 0x49, 0x75, 0x4e, 0xcc, 0xc9, 0x09, 0x4a, 0x2d, 0x14, 0x12, 0xe1, 0x62, 0xf5,
	0x2d, 0x4e, 0xf7, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70, 0x84, 0x84, 0xb8,
	0x58, 0x5c, 0x12, 0x4b, 0x12, 0x25, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0xc0, 0x6c, 0x21, 0x31,
	0x2e, 0x36, 0x90, 0x26, 0xcf, 0x14, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x28, 0x0f, 0xd5,
	0x48, 0xc7, 0xe4, 0x6c, 0xca, 0x8d, 0x4c, 0x62, 0x03, 0xbb, 0xd8, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x16, 0xa8, 0x05, 0x14, 0xbe, 0x00, 0x00, 0x00,
}
