// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relay.proto

package relay

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RelayAck struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	MsgId                int32    `protobuf:"varint,2,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	Bytes                []byte   `protobuf:"bytes,3,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	Int64                int64    `protobuf:"varint,4,opt,name=Int64,proto3" json:"Int64,omitempty"`
	Int64Slice           []int64  `protobuf:"varint,5,rep,packed,name=Int64Slice,proto3" json:"Int64Slice,omitempty"`
	Str                  string   `protobuf:"bytes,6,opt,name=Str,proto3" json:"Str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayAck) Reset()         { *m = RelayAck{} }
func (m *RelayAck) String() string { return proto.CompactTextString(m) }
func (*RelayAck) ProtoMessage()    {}
func (*RelayAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f69a7d5a802d584, []int{0}
}

func (m *RelayAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayAck.Unmarshal(m, b)
}
func (m *RelayAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayAck.Marshal(b, m, deterministic)
}
func (m *RelayAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayAck.Merge(m, src)
}
func (m *RelayAck) XXX_Size() int {
	return xxx_messageInfo_RelayAck.Size(m)
}
func (m *RelayAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayAck.DiscardUnknown(m)
}

var xxx_messageInfo_RelayAck proto.InternalMessageInfo

func (m *RelayAck) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *RelayAck) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *RelayAck) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *RelayAck) GetInt64() int64 {
	if m != nil {
		return m.Int64
	}
	return 0
}

func (m *RelayAck) GetInt64Slice() []int64 {
	if m != nil {
		return m.Int64Slice
	}
	return nil
}

func (m *RelayAck) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func init() {
	proto.RegisterType((*RelayAck)(nil), "relay.RelayAck")
}

func init() { proto.RegisterFile("relay.proto", fileDescriptor_9f69a7d5a802d584) }

var fileDescriptor_9f69a7d5a802d584 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4a, 0xcd, 0x49,
	0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x26, 0x30, 0x72, 0x71,
	0x04, 0x81, 0x58, 0x8e, 0xc9, 0xd9, 0x42, 0x02, 0x5c, 0xcc, 0xbe, 0xc5, 0xe9, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x3c, 0x41, 0x20, 0xa6, 0x90, 0x08, 0x17, 0xab, 0x6f, 0x71, 0xba, 0x67, 0x8a, 0x04,
	0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x84, 0x03, 0x12, 0x75, 0xaa, 0x2c, 0x49, 0x2d, 0x96, 0x60,
	0x06, 0xab, 0x84, 0x70, 0x40, 0xa2, 0x9e, 0x79, 0x25, 0x66, 0x26, 0x12, 0x2c, 0x0a, 0x8c, 0x1a,
	0xcc, 0x41, 0x10, 0x8e, 0x90, 0x1c, 0x17, 0x17, 0x98, 0x11, 0x9c, 0x93, 0x99, 0x9c, 0x2a, 0xc1,
	0xaa, 0xc0, 0xac, 0xc1, 0x1c, 0x84, 0x24, 0x02, 0xb2, 0x33, 0xb8, 0xa4, 0x48, 0x82, 0x4d, 0x81,
	0x51, 0x83, 0x33, 0x08, 0xc4, 0x4c, 0x62, 0x03, 0x3b, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x1c, 0x9b, 0x83, 0xe8, 0xaf, 0x00, 0x00, 0x00,
}
